### ISSUE TITLE
Weird camel casing

### ISSUE THREAD

**Issue by nidu** [JamesNK/Newtonsoft.Json#832] opened 2016-03-03 10:09 UTC
Hello, i stumbled upon interesting serialization result with camel case resolver. Consider following code sample:

```c#
var settings = new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() };
Assert.AreEqual("{\"vmQ\":1,\"mphQ\":2}", JsonConvert.SerializeObject(new { VmQ = 1, MphQ = 2 }, settings));
```

Test fails with following message:

```
Assert.AreEqual failed. Expected:<{"vmQ":1,"mphQ":2}>. Actual:<{"vmq":1,"mphQ":2}>.
```

Shouldn't `VmQ` be serialized as `vmQ`?

Version is 8.0.2

**Comment by Tydude4Christ** [comment] 2016-03-04 01:11
Dupe of #828

**Comment by nidu** [comment] 2016-03-04 04:06
@Tydude4Christ thanks

**Comment by JamesNK** [comment] 2016-03-04 08:36
Fixed

**Closed by JamesNK** 2016-03-04 08:36 UTC
