### ISSUE TITLE
serializes a DataSet to JSON on dotnet core 2.0

### ISSUE THREAD

**Issue by yangyachao** [JamesNK/Newtonsoft.Json#1409] opened 2017-08-28 04:04 UTC
<img width="1582" alt="2017-08-28 12 01 49" src="https://user-images.githubusercontent.com/4145688/29758802-fc1443d4-8b7b-11e7-8cf1-895426de60a8.png">

**Comment by TimRowe** [comment] 2017-09-14 05:49
I have the same problem when convert datatable to json on .net core 2.0. Any one help?

**Comment by moh-hassan** [comment] 2017-09-20 22:18
The issue is due to the serializer don't use the DataSetConverter in netcore 2.0 (the current support of json.net v10.0.3 is netstandard 1.3)

I have used the same source code of  DataSetConverter/DataTableConverter  in a separate project created in dotnet core 2.0 (with some modification ) and json is created  normally as expected.

I hosted the demo project in [github](https://github.com/moh-hassan/DataTableCor2).
You can use the accompanied library until it's implemented in the next release.
The generated json is:

			{
			  "table1": [
				{
				  "id": 0,
				  "item": "item 0"
				},
				{
				  "id": 1,
				  "item": "item 1"
				}
			  ]
			}
	
I expect, once Json.Net support netcore 2.0 (which is final release), DataSetConverter/DataTableConverter will be available.

**Comment by yangyachao** [comment] 2017-09-21 06:56
@moh-hassan  Thank you so much ，But there is still a small problem,When the columnValue is DBNull
![084101f8-0e48-4323-a72c-f55368f6372f](https://user-images.githubusercontent.com/4145688/30682635-fb146368-9e6f-11e7-99d8-35ef1abe21aa.png)

**Comment by moh-hassan** [comment] 2017-09-21 18:10
DBNull is supported in netstandard2 (netcore 2)
Review the source code [public sealed class DBNull : ISerializable, IConvertible](https://source.dot.net/#System.Private.CoreLib/shared/System/DBNull.cs,7faae4cef0a3f251)
 
If you serialized  the dataset to xml , `dataSet.WriteXml(textwriter) you get xml without error in case some columns have DBNull values.

I think this error is related to the internals of json.net of handling DBNull, and  waiting to the update  of other packages to netstandard2 that json.net depends on like: System.Runtime.Serialization.Primitives, System.ComponentModel.TypeConverter

You can avoid this error by  supplying settings to JsonConvert.SerializeObject to tell it how to handle null values:

              var settings = new JsonSerializerSettings
                    {
                        NullValueHandling = NullValueHandling.Ignore,
                        MissingMemberHandling = MissingMemberHandling.Ignore
                    };
               settings.Converters.Add(new DataSetConverter()); // using the acompanied library
               var json = JsonConvert.SerializeObject(dataSet, settings);

I updated my demo in [github ](https://github.com/moh-hassan/DataTableCor2) to handle DBnull and generate a corresponding xml serialization.

**Comment by JamesNK** [comment] 2017-10-01 10:30
It will be fixed with a netstandard20 assembly - https://github.com/JamesNK/Newtonsoft.Json/commit/ab3315f1d5e57c70203c904be79d8e951bf09794

**Closed by JamesNK** 2017-10-01 10:30 UTC
Labels: netstandard20

**Comment by kfarris9** [comment] 2017-11-20 18:33
Is there a target date for when an 11.x version of Newtonsoft.Json will be available on Nuget (even as prerelease)?

**Comment by EvanCarroll** [comment] 2017-12-29 08:37
@kfarris9 there is a version up now, (been up for a while)

https://www.nuget.org/packages/Newtonsoft.Json/11.0.1-beta1

**Comment by pranavagg** [comment] 2018-01-19 11:18
When is the next stable build release in which this change set is included?
