### ISSUE TITLE
Failed to Load Schema with Self Reference

### ISSUE THREAD

**Issue by Myrkai** [JamesNK/Newtonsoft.Json#1892] opened 2018-10-23 09:41 UTC
### Source types
```csharp
types.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "types.json#",
	"definitions": {
		"Location": {
			"type": "object",
			"properties": {
				"address": {
					"type": "string",
					"minLength": 1,
					"maxLength": 255
				},
				"location": {
					"type": "string",
					"minLength": 1,
					"maxLength": 255
				},
				"status": {
					"$ref": "types.json#/definitions/Status"
				}
			}
		},
		"Status": {
			"type": [ "object", "null" ],
			"properties": {
				"reason": {
					"type": "string",
					"minLength": 1
				},
				"description": {
					"type": [
						"string",
						"null"
					],
					"minLength": 1,
					"maxLength": 255
				}
			},
			"required": [
				"reason",
				"description"
			]
		}
	}
}

sample.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "sample.json#",
	"type": "object",
	"allOf": [
		{ "$ref": "types.json#/definitions/Location" },
		{
			"properties": {
				"subLocations": {
					"type": "array",
					"items": { "$ref": "types.json#/definitions/Location" }
				}
			},
			"required": [
				"address",
				"location",
				"subLocations"
			]
		}
	]
}

```

### Function to load the Schema
```csharp
private static JSchema ReadSchema(String filepath)
{
	JSchema schema;
	var resolver = new JSchemaPreloadedResolver();

	using (StreamReader typesReader = new StreamReader("types.json")) {
		resolver.Add(new Uri("types.json", UriKind.Relative), typesReader.BaseStream);

		using (StreamReader streamReader = new StreamReader(filepath)) {
			using (JsonTextReader reader = new JsonTextReader(streamReader)) {
				schema = JSchema.Load(reader,
					new JSchemaReaderSettings() {
						Resolver = resolver,
						ResolveSchemaReferences = true
					});
			}
		}
	}

	return schema;
}
```
### Expected behavior
I want to load JSchema with self-reference.

### Actual behavior
After load following Exception occurred: 
I want to load the Schema with self-reference.
Newtonsoft.Json.Schema.JSchemaReaderException
  HResult=0x80131500
  Nachricht = Error when resolving schema reference 'types.json#/definitions/Location'. Path 'allOf[0]', line 6, position 3.
  Quelle = Newtonsoft.Json.Schema
  Stapelüberwachung:
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ResolveDeferedSchema(DeferedSchema deferedSchema)
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ResolveDeferedSchemas()
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ReadRoot(JsonReader reader, Boolean resolveDeferedSchemas)
   at Program.ReadSchema(String filepath)

Innere Ausnahme 1:
JSchemaReaderException: Could not resolve schema reference 'types.json#/definitions/Status'. Path 'definitions.Location.properties.status', line 18, position 15.
### Steps to reproduce
```csharp
var schema = ReadSchema("sample.json");
```

**Comment by xavier-rigau** [comment] 2019-03-25 17:35
I have a very similar issue with a sel-referencing schema. It works in all platforms and validation libs we have but Newtonsoft.Json.

`{
  "id":"http://schemaregistry.analysis.ext.hp.com/cdm/id/eventing-event-schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/event",
  "definitions": {
    "event": {
      "title": "event",
      "type": "object",
      "properties": {
        "version": {
          "$ref": "commonGlossary-schema.json#/definitions/version"
        },
        "eventCategory": {
          "$ref": "#/definitions/eventCategory"
        },
...
}` 

Visual Studio says I cannot resolve both these lines (squiggly green line)

 "$ref": "#/definitions/event",

and 

  "$ref": "#/definitions/eventCategory"

The exception is 

`Newtonsoft.Json.Schema.JSchemaReaderException: Error when resolving schema reference '#/definitions/event'. Path '', line 1, position 1. ---> Newtonsoft.Json.Schema.JSchemaReaderException: Could not resolve schema reference 'http://schemaregistry.analysis.ext.hp.com/cdm/id/eventing-event-schema.json#/definitions/event'. Path '', line 1, position 1.
`

**Comment by JanKinable** [comment] 2019-11-06 13:03
Same here. This one is open for more than a year. Is someone looking at it?

**Comment by JamesNK** [comment] 2019-11-09 00:18
Fixed here - https://github.com/JamesNK/Newtonsoft.Json.Schema/pull/199

The problem is the trailing `#` on the root schema ID: `"$id": "types.json#"`

Until a fixed version comes out you can workaround the problem by removing the `#`: `"$id": "types.json"`

**Closed by JamesNK** 2019-11-09 00:18 UTC

**Comment by xavier-rigau** [comment] 2020-01-14 17:50
I still have the same issue with version 3.0.11.  Where can I send a sample project?

**Comment by tkurskiev** [comment] 2020-12-06 02:05
Hi to all!

Regarding that problem with '$ref" not working - this nuger recognizes '$def' keyword, use it instead of 'definitions', example:

`{
  '$defs':{
    'address': {
      'type': 'object',
      'properties': {
        'street_address': { 'type': 'string' },
        'city':           { 'type': 'string' },
        'state':          { 'type': 'string' }
      },
      'required': ['street_address', 'city', 'state']
    },
      'car':{'type':'string'}
  },
  
  'description': 'A person',
  'type': 'object',
  'additionalProperties':false,
  'properties':
  {
    'name': {'type':'string'},
    'hobbies': {
      'type': 'array',
      'items': {'type':'string'}
    }
  },
    '$ref': '#/$defs/address'
}`
