### ISSUE TITLE
Deserialize multiple json objects in one json string

### ISSUE THREAD

**Issue by DimitriM** [JamesNK/Newtonsoft.Json#2125] opened 2019-08-09 16:10 UTC
For deserialising multiple json objects in one json string I use the following function:

```csharp
private IEnumerable<T> DeserializeObjects<T>(TextReader textReader, JsonSerializerSettings settings = null)
{
	var ser = JsonSerializer.CreateDefault(settings);
	var reader = new JsonTextReader(textReader);

	reader.SupportMultipleContent = true;

	while (reader.Read())
	{
		if (reader.TokenType == JsonToken.None || reader.TokenType == JsonToken.Undefined || reader.TokenType == JsonToken.Comment)
			continue;
		yield return ser.Deserialize<T>(reader);
	}
}
```

When I deserialize 2 complete json objects in one string it works perfectly:

```json
{"dus":null,"due":null,"rtk":{"rva":false,"rac":true}}{"dus":null,"due":null,"rtk":{"rva":false,"rac":true}}
```

When the first object is not complete like:

```json
{"rva":false,"rac":true}}{"dus":null,"due":null,"rtk":{"rva":false,"rac":true}}
```

The parser does something wrong and the CPU usage of the thread goes to 100%

**Comment by JamesNK** [comment] 2019-08-18 08:28
I couldn't reproduce this. With your code (deserializing into `object`) and JSON I got a reader error: `JsonToken EndObject is not valid for closing JsonType None. Path '', line 1, position 25.`

**Closed by JamesNK** 2019-08-18 08:28 UTC

**Comment by dzmitry-lahoda** [comment] 2021-08-23 14:41
and it seems split is natively supported https://www.newtonsoft.com/json/help/html/ReadMultipleContentWithJsonReader.htm
