### ISSUE TITLE
Support async serialization and deserialization

### ISSUE THREAD

**Issue by Gchkh16** [JamesNK/Newtonsoft.Json#2376] opened 2020-08-13 11:47 UTC
It will be very good feature to add `async `serialization and deserialization from `Stream`. Current `JsonSerializer` don't have such feature and you have to work synchronously with `Stream`, when in most cases source of `Stream` is network or hard disk.

**Comment by sungam3r** [comment] 2020-08-13 21:03
I don't think such a feature will ever appear. Generally speaking, it is unlikely that anything serious will appear in this project - the focus has switched to the development of System.Text.Json (async, fast, allocation free span-driven implementation), and Newtonsoft.Json recommended to be used only for legacy projects. So we can probably only expect some critical bugs to be fixed, but not new features. Backward compatibility and stability are a priority here. @JamesNK, do I understand the development strategy correctly?

**Comment by JamesNK** [comment] 2020-08-13 21:10
Dupe of https://github.com/JamesNK/Newtonsoft.Json/issues/1193

Doing it properly would require completely rewriting the JSON reader and JSON serializer. I don't want to do that because it would basically be a new serializer. And doing it quickly would have bad performance and introduce a lot of code duplicate.

Basically I don't have any plan to do have an async serializer.

**Closed by JamesNK** 2020-08-13 21:10 UTC
