### ISSUE TITLE
Populate fails to overwrite JToken value with mismatched type

### ISSUE THREAD

**Issue by ejball** [JamesNK/Newtonsoft.Json#2512] opened 2021-04-14 17:52 UTC
### Source/destination types

```csharp
class HasToken
{
	public JToken? Value { get; set; }
}
```

### Source/destination JSON

```javascript
{"value":{}}
```

### Expected behavior

`Value` should be a `JObject`.

### Actual behavior

If `Value` was already set to a `JToken` that isn't a `JObject`, `Populate` fails with this exception: `JsonSerializationException: Deserialized JSON type 'Newtonsoft.Json.Linq.JObject' is not compatible with expected type 'Newtonsoft.Json.Linq.JArray'.`

This started happening with 13.0.1, presumably due to #2494.

### Steps to reproduce

```csharp
var jToken = JToken.Parse(@"{""value"":{}}");
var hasToken = new HasToken { Value = new JArray() };
JsonSerializer.Create().Populate(jToken.CreateReader(), hasToken);
```

**Comment by JamesNK** [comment] 2021-05-14 23:28
Duplicate of https://github.com/JamesNK/Newtonsoft.Json/issues/2529

**Closed by JamesNK** 2021-05-14 23:28 UTC
