### ISSUE TITLE
ShouldSerializeAProperty() method not called if marked as internal

### ISSUE THREAD

**Issue by goldmont** [JamesNK/Newtonsoft.Json#1941] opened 2018-12-14 10:12 UTC
Hi,

following [your](https://www.newtonsoft.com/json/help/html/conditionalproperties.htm) guide about ignoring properties at runtime, I faced a problem with the **internal** access modifier. If the method **ShouldSerializeManager()** is marked as **internal**, then the library won't invoke it even if I put the following assembly's attribute on my namespace:
```csharp
[assembly: InternalsVisibleTo("Newtonsoft.Json")]
```

This works:
```csharp
public class Employee
{
    public string Name { get; set; }
    public Employee Manager { get; set; }

    // Called!
    public bool ShouldSerializeManager()
    {
        // don't serialize the Manager property if an employee is their own manager
        return (Manager != this);
    }
}
```

This one not:
```csharp
[assembly: InternalsVisibleTo("Newtonsoft.Json")]
namespace SomeNamespace
{
    public class Employee
    {
        public string Name { get; set; }
        public Employee Manager { get; set; }

        // Never called!
        internal bool ShouldSerializeManager()
        {
            // don't serialize the Manager property if an employee is their own manager
            return (Manager != this);
        }
    }
}
```

I think this is due to reflection queries filters. You should also filter by internal fields, not only public ones.

Thanks for your efforts.

Best regards.

**Comment by peppe130** [comment] 2018-12-14 10:33
I think the issue is [here](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L1629).

Calling **GetMethod()** without specifying any **BindingFlags**, will result in a query for all and only public fields. You should specify something like **BindingFlags.Instance**.

**Comment by ddrdoubled** [comment] 2019-03-21 07:06
Duplicate of #1324

**Comment by JamesNK** [comment] 2019-03-21 14:36
Closing as a duplicate

**Closed by JamesNK** 2019-03-21 14:36 UTC
