### ISSUE TITLE
ReferenceLoopHandling.Ignore not working

### ISSUE THREAD

**Issue by jrrcdev** [JamesNK/Newtonsoft.Json#1929] opened 2018-11-30 11:02 UTC
Hello, I have an Asp.Net Core with version 2.1 and the ReferenceLoopHandling.Ignore is not working or it is working really late, I have an object model like this:

Product.ProductItems[0].Product.ProductItems[0].Product......

It's causing a huge Json file, which has more than 1GB. I check the ReferenceLoopHandling.Error setting and it throws the error, like expected, with ReferenceLoopHandling.Serialize, the application stops. First I think it was a Aspnet.core issue, because the json returned on a GET request was too big, but after I tried to serialize it before return and got the same error. I tried with version 11 and 12.

My Serialize function:
```csharp
public static string Serialize(this object value)
        {
            return JsonConvert.SerializeObject(value, new JsonSerializerSettings()
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                DateTimeZoneHandling = DateTimeZoneHandling.Utc,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }
```

### Expected behavior

Expect loop values to be excluded from serialization

### Actual behavior

Serialize loop values

**Comment by yakeer** [comment] 2019-01-10 10:37
Having this issue as well, Have you succeeded in figure out what is it happening?
Or even better, how to avoid it?

**Comment by ks1974in** [comment] 2019-05-10 12:16
I am trying to serialize a structure using Newtonsoft.json. I have a collection of tables in memory. I am trying to serialize it to JSON using Newtonsoft.json. I am also using NHibernate,  FluentNHibernate and NHibernatePropertyChanged. I had a problem with NHibernate and so checked what was happening in the NHibernate source code from the repository. Apart from that issue with NHibernate , which I have bypassed for the present, I found that a specific property getter "dentitySelectString" in class "AbstractCollectionPersister"  in the NHibernate code gets called repeatedly. There seems to be an infinite loop in the serialization process, as reported in this issue. Is there any solution to this?

**Comment by RemyArmstro** [comment] 2020-01-16 19:40
I am having this same issue with a data structure being returned from EF Core.  I turn on "Error" handling, and it fails.  I leave it on "Ignore" and I get a very very large memory consumption that finally blows up due to out of memory.

**Comment by satishviswanathan** [comment] 2020-01-20 23:58
I'm facing the same issue too, looks like ReferenceLoopHandling.Ignore is not working. Did anybody get it working? Any help is appreciated.

**Comment by manit77** [comment] 2020-02-26 23:27
even the documentation shows its not working. The result show be:

// {
//   "Name": "Joe User",
// }

https://www.newtonsoft.com/json/help/html/ReferenceLoopHandlingIgnore.htm

public class Employee
{
    public string Name { get; set; }
    public Employee Manager { get; set; }
}

string json = JsonConvert.SerializeObject(joe, Formatting.Indented, new JsonSerializerSettings
{
    ReferenceLoopHandling = ReferenceLoopHandling.Ignore
});

Console.WriteLine(json);
// {
//   "Name": "Joe User",
//   "Manager": {
//     "Name": "Mike Manager"
//   }
// }

**Comment by TurmanTech** [comment] 2020-04-12 02:33
> I am having this same issue with a data structure being returned from EF Core. I turn on "Error" handling, and it fails. I leave it on "Ignore" and I get a very very large memory consumption that finally blows up due to out of memory.

Did anyone find a fix for this? I'm having the exact same issue as well, and the object being serialized doesn't even have any navigation properties. Leaving ReferenceLoopHandling.Ignore enabled causes a memory surge & crash, whereas leaving it out causes the error "Self referencing loop detected".

**Comment by AStove** [comment] 2020-08-03 15:16
Having this aswell. Maybe part of the problem is, it's not a direct self reference. The loop is like this: A -> List of B -> C -> A. There's multiple loops too. For me the memory doesn't explode. It just never finishes and the CPU is high. When breaking the process and stepping it just goes over every get properties over and over again.

![image](https://user-images.githubusercontent.com/23409814/89197888-b0788100-d5ac-11ea-8b71-ab5d3a2ed945.png)

How deep does this ReferenceLoopHandling.Ignore look to know it's looping?

**Comment by prabinKshrestha** [comment] 2021-03-06 14:22
I am facing the same problem in .NET Core Web API and EF Core. I have Data layer which has repository, service layer and controller layer. Entity is used for database and used in data and service layer and DTOs for API response. I am using Automapper for mapping Entity and DTOs. When I do Eager loading and return Entity then it is working fine. When I return the DTO after mapping using Automapper then response take infinite time to throw response. I also checked by assigning the automapped DTOs to variable and then return variable in response and found that automapping is not taking time. Only sending response is taking lots of time. Lazy loading is disabled and Reference loop handling is also ingored .

**Comment by JamesNK** [comment] 2021-03-09 06:02
> even the documentation shows its not working. The result show be:
> 
> // {
> // "Name": "Joe User",
> // }
> 
> [newtonsoft.com/json/help/html/ReferenceLoopHandlingIgnore.htm](https://www.newtonsoft.com/json/help/html/ReferenceLoopHandlingIgnore.htm)
> 
> This sample sets ReferenceLoopHandling to Ignore so that looping values are excluded from serialization instead of throwing an exception.
> 
> public class Employee
> {
> public string Name { get; set; }
> public Employee Manager { get; set; }
> }
> 
> string json = JsonConvert.SerializeObject(joe, Formatting.Indented, new JsonSerializerSettings
> {
> ReferenceLoopHandling = ReferenceLoopHandling.Ignore
> });
> 
> Console.WriteLine(json);
> // {
> // "Name": "Joe User",
> // "Manager": {
> // "Name": "Mike Manager"
> // }
> // }

It works fine: https://dotnetfiddle.net/9fP69b

**Comment by JamesNK** [comment] 2021-03-09 06:03
> I am facing the same problem in .NET Core Web API and EF Core. I have Data layer which has repository, service layer and controller layer. Entity is used for database and used in data and service layer and DTOs for API response. I am using Automapper for mapping Entity and DTOs. When I do Eager loading and return Entity then it is working fine. When I return the DTO after mapping using Automapper then response take infinite time to throw response. I also checked by assigning the automapped DTOs to variable and then return variable in response and found that automapping is not taking time. Only sending response is taking lots of time. Lazy loading is disabled and Reference loop handling is also ingored .

I am 99% sure your issue is in EF, not Newtonsoft.Json.

I'm closing this issue. If someone has a reproduction of this issue that doesn't involve an external library like Entity Framework or AutoMapper then I'll reopen it.

**Closed by JamesNK** 2021-03-09 06:03 UTC

**Comment by nokternol** [comment] 2021-06-04 11:18
We have just run into this issue ourselves and I can confirm that something is not right but it neither lives on EF's side nor Netwonsoft's.. They just do not play nicely in one specific scenario.

It is not identical to the OP as we do not get an exception thrown when the value is set to ignore..
Instead the serializer loops until it runs out of memory trying.

If set to Error it throws as expected.

The scenario is when a DbQuery is provided directly to the serializer.
In this scenario... (WARNING: The following is speculation)
Newtonsoft walks the object tree to figure out what needs to be serialized triggering EF Lazy Loading behaviour expanding the model to include ALL children and if a circular reference is found it just keeps going.

If you materialize the query beforehand however this result does not occur and the references are ignored as expected.
Is this a known limitation when combining EF and Newtonsoft?
Obviously this is easily avoidable by never passing a DbQuery back from your controller and instead materializing the result first.

**Comment by THammond9** [comment] 2025-07-08 21:38
> We have just run into this issue ourselves and I can confirm that something is not right but it neither lives on EF's side nor Netwonsoft's.. They just do not play nicely in one specific scenario.
> 
> It is not identical to the OP as we do not get an exception thrown when the value is set to ignore.. Instead the serializer loops until it runs out of memory trying.
> 
> If set to Error it throws as expected.
> 
> The scenario is when a DbQuery is provided directly to the serializer. In this scenario... (WARNING: The following is speculation) Newtonsoft walks the object tree to figure out what needs to be serialized triggering EF Lazy Loading behaviour expanding the model to include ALL children and if a circular reference is found it just keeps going.
> 
> If you materialize the query beforehand however this result does not occur and the references are ignored as expected. Is this a known limitation when combining EF and Newtonsoft? Obviously this is easily avoidable by never passing a DbQuery back from your controller and instead materializing the result first.

This seems like pretty good guess. We ran into this behavior as well and for us, even though the object was materialized, it was being tracked and that caused the problem. Added `AsNoTracking()` and got the expected behavior.
