### ISSUE TITLE
Read-only wrapper for J objects

### ISSUE THREAD

**Issue by rohitlodha** [JamesNK/Newtonsoft.Json#721] opened 2015-11-22 06:40 UTC
Are there any read-only wrapper for JObject? I see it is not trivial to write one.

**Comment by JamesNK** [comment] 2015-11-28 07:00
Closing as duplicate of https://github.com/JamesNK/Newtonsoft.Json/issues/468

**Closed by JamesNK** 2015-11-28 07:00 UTC
