### ISSUE TITLE
Root object type is not written with TypeNameHandling.Auto

### ISSUE THREAD

**Issue by shift-evgeny** [JamesNK/Newtonsoft.Json#1128] opened 2017-01-04 13:34 UTC
When **TypeNameHandling** is set to **Auto** the serializer writes the object types for any contained objects, which enables derived types to be deserialized correctly. However, it doesn't write the type for the root object, so this fails unless the caller somehow knows the exact type. It would be very useful if TypeNameHandling.Auto wrote $type for the root object, too.

Note that the deserializer already supports this. If I manually add the $type property it works.

The following LINQPad snippet demonstrates the problem:

```
public abstract class MyBase
{
	public string BaseProperty { get; set; }
}

public class MyDerived : MyBase
{
	public string DerivedProperty { get; set; }
}

public class Container
{
	public MyBase Contained { get; set; }
}

private void RoundtripObject<T>(T original)
{
	var settings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.Auto };
	var json = JsonConvert.SerializeObject(original, settings);
	json.Dump();

	var deserialized = JsonConvert.DeserializeObject<T>(json, settings);
	deserialized.Dump();
}

void Main()
{
	MyBase contained = new MyDerived { BaseProperty = "base", DerivedProperty = "derived" };
	var container = new Container { Contained = contained };
	// JSON: {"Contained":{"$type":"UserQuery+MyDerived, ...","DerivedProperty":"derived","BaseProperty":"base"}}
	RoundtripObject(container);	// OK
	// JSON (no type for root object!): {"DerivedProperty":"derived","BaseProperty":"base"}
	RoundtripObject(contained); // Error: Could not create an instance of type UserQuery+MyBase. Type is an interface or abstract class and cannot be instantiated. Path 'DerivedProperty', line 1, position 19.
	
	// Deserialization works fine if the type is there
	var jsonWithType = "{\"$type\":\"UserQuery+MyDerived, " + GetType().Assembly.GetName().Name + "\",\"DerivedProperty\":\"derived\",\"BaseProperty\":\"base\"}";
	var deserializedWithType = JsonConvert.DeserializeObject<MyBase>(jsonWithType, new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.Auto });
	deserializedWithType.Dump();
}
```

**Comment by TylerBrinkley** [comment] 2017-01-04 13:51
Duplicate of #990. I think this is one of the biggest gotcha's when working with Json.NET which is why I proposed adding generic versions of SerializeObject in #634 which would have fixed this issue. Unfortunately, it was decided not to be added.

**Comment by shift-evgeny** [comment] 2017-01-04 13:58
Hmm... #990 says "You can however specify a type argument for the root type in one of the SerializeObject overloads which will achieve what you want." but I've just tried that: 
```var json = JsonConvert.SerializeObject(original, original.GetType(), settings);```
and the resulting JSON still doesn't include the type: 
```{"DerivedProperty":"derived","BaseProperty":"base"}```

**Comment by TylerBrinkley** [comment] 2017-01-04 15:02
You want to use this instead:
`var json = JsonConvert.SerializeObject(original, typeof(T), settings);`

**Comment by shift-evgeny** [comment] 2017-01-04 17:54
OK, that works, but it seems really confusing. I can basically pass in any type *except* the actual object type and `SerializeObject` writes the type to JSON. E.g. this works:
```var json = JsonConvert.SerializeObject(original, typeof(DBNull), settings);```
Result:
```{"$type":"UserQuery+MyDerived, query_ocekut","DerivedProperty":"derived","BaseProperty":"base"}```

So should I just pass some random type in, e.g. `typeof(object)`? What exactly is the "declared" type here?

**Comment by TylerBrinkley** [comment] 2017-01-04 18:02
Your declared type is `MyBase` as that is the variable `contained`'s type.

Remember `TypeNameHandling.Auto` only outputs the type info if the object's runtime type doesn't match its declared type such as the property `Contained` is declared as a `MyBase` but its runtime type in this case was `MyDerived`.

**Comment by shift-evgeny** [comment] 2017-01-04 18:10
Sure, in this case it's simple, but it could be a much more complex type hierarchy and there could be templates, too. E.g. if the object is actually `MyDerived<DerivedItem>`, inheriting from `MyBase<TItem>` where `TItem` is a type parameter and MyBase itself inherits from `MySuperBase<TItem, string>`, etc. - what's the "declared type" then?

All I want, in the end, is to get back the exact same type after deserializing. At serialization time that just means I want the `$type` written.

**Comment by TylerBrinkley** [comment] 2017-01-04 18:24
For a root object, the declared type would be the type of the variable you're passing to SerializeObject. This confusion just goes to show how much we need generic SerializeObject methods as proposed in #634.

**Comment by shift-evgeny** [comment] 2017-01-04 18:34
I don't see how the type of the variable matters. It could anything in the type hierarchy of the input object, including `System.Object`! This doesn't tell me the right value to pass in or, more precisely, what is the difference in behaviour between passing in `typeof(MyBase)`, `typeof(MySuperBase)`, `typeof(object)` and `typeof(DBNull)`.

**Comment by TylerBrinkley** [comment] 2017-01-04 18:36
In other words, the declared type should be the type you're going to specify in the `DeserializeObject` method.

**Comment by shift-evgeny** [comment] 2017-01-04 18:44
That makes more sense. I really just want it to read the type from the JSON and `JsonConvert.DeserializeObject<System.Object>` seems to work fine for that. So is there any reason to specify a more derived type than object (other than to avoid casting it later)?

**Comment by TylerBrinkley** [comment] 2017-01-04 18:48
I suppose not but I'd prefer not to cast.

**Comment by shift-evgeny** [comment] 2017-01-04 18:49
OK, so then my earlier question remains: is there any reason to pass any type other than `System.Object` to `SerializeObject()`?

**Comment by TylerBrinkley** [comment] 2017-01-04 19:01
I suppose not if you want the type info serialized no matter what for the root object. You don't actually need the type info on the root object if the type you're deserializing to is the actual type of the object.

**Comment by shift-evgeny** [comment] 2017-01-05 10:15
OK, then I suppose it works, albeit in a highly un-intuitive way. :)

**Closed** 2017-01-18 21:40 UTC
