### ISSUE TITLE
Slow deserialization on first use on Android only

### ISSUE THREAD

**Issue by KyleTraynor** [JamesNK/Newtonsoft.Json#1326] opened 2017-05-25 21:05 UTC
Using JSON.NET with Xamarin with .net standard 1.6, the first use of deserialization is very slow (10+ seconds), but subsequent deserialization of the exact same json is very fast, on Android only. On iOS it is always fast.

There are several reports by different users with the same issue, some reporting reverting to json.net 8.0.3 fixing the problem, some saying it does not.

See some users here:
https://stackoverflow.com/questions/42285254/json-net-slow-on-first-use-on-xamarin-android
https://forums.xamarin.com/discussion/95688/very-slow-in-xamarin-forms-android-app-while-doing-deserializeobject
https://forums.xamarin.com/discussion/comment/272208/#Comment_272208

I have this problem on 10.02 and 9.0.1. I am unable to downgrade to 8.0.3 because it is not .net standard compatible.

**Comment by chrisfoulds** [comment] 2017-06-12 09:59
I also have the same issue, was able to drop back to 8.0.3, it's all over the xamarin threads

**Comment by JamesNK** [comment] 2017-06-17 02:25
It sounds like it is fixed in VS 15.2 https://bugzilla.xamarin.com/show_bug.cgi?id=56240

Can this be closed?

**Comment by chrisfoulds** [comment] 2017-06-17 05:14
I am running the latest versions on Xamarin and Mono available, but still with 10.0.2 I get a major slowdown on deserialization on the first run, yet on 8.0.3 I don't encounter any issue.

**Comment by JamesNK** [comment] 2017-06-17 08:14
Well I don't know Android and I don't have time to learn and setup and environment. If someone else figures it out and submits a PR that fixes whatever the issue is then I'm happy to accept it.

**Comment by JamesNK** [comment] 2018-01-01 20:13
I've copied the issue to the Xamarin Android github project.

**Closed by JamesNK** 2018-01-01 20:13 UTC

**Comment by jonpryor** [comment] 2018-01-02 20:53
This is not a per-se Xamarin.Android problem. This is a *JIT overhead* problem, and Xamarin.Android is a JIT environment, as is desktop .NET and desktop Mono.

Console test app: [gxa-1147.zip](https://github.com/JamesNK/Newtonsoft.Json/files/1598648/gxa-1147.zip)

Usage:

    $ nuget restore gxa-1147.sln
    $ msbuild gxa-1147.sln
    $ mono gxa-1147/bin/Debug/gxa-1147.exe gxa-1147/people.json gxa-1147/people.json
    Parsing: gxa-1147/people.json
            Name: Santa Claus
            Name: The Grinch
            Name: Easter bunny
            Name: Tooth ferry
      Total time: 129ms
    Parsing: gxa-1147/people.json
            Name: Santa Claus
            Name: The Grinch
            Name: Easter bunny
            Name: Tooth ferry
      Total time: 0ms

`gxa-1147.exe` will parse each file specified on the command line, and
print out how long it took to process and print out the contents of
the file. Notice that:

 1. The same file is specified on the command-line twice, so that the
    same file is processed twice, and
 2. The first file parsing is *much* slower than the second.

The reason that "first use deserialization" isn't slow on iOS is because there's no JIT on iOS: everything is AOT'd.

This is *not* a Xamarin.Android bug. This is a fact of life of JIT environments: there is a JIT, it has associated startup overheads, and the first time a method/etc. is hit, it must be JIT'd.

**Comment by JamesNK** [comment] 2018-01-02 20:55
JIT shouldn't take 10 seconds.

And why does Android deserialize an object almost instantly with Newtonsoft.Json 8.03 but takes 10 seconds with 10.0.3?

**Comment by jonpryor** [comment] 2018-01-02 20:58
> JIT shouldn't take 10 seconds.

Have a sample where it is? I was looking at [this sample](https://github.com/monostefan/json.net_android_slow_start), linked to from [stackoverflow](https://stackoverflow.com/questions/42285254/json-net-slow-on-first-use-on-xamarin-android) (in the original description), and it wasn't taking 10 seconds; initial use was 300-400ms.

**Comment by deakjahn** [comment] 2018-12-01 10:54
James, you ask *us*? :-)

Could the last comment of https://github.com/xamarin/xamarin-android/issues/1147 help?

**Comment by omghb** [comment] 2023-11-08 09:07
I can confirm that this issue still exist with MAUI 7 / .NET for Android 7. Our solutions uses the default build settings (enabled AOT).

See [Release builds default to the following AOT property values](https://learn.microsoft.com/en-us/dotnet/maui/migration/android-projects)
```
<PropertyGroup Condition="'$(Configuration)' == 'Release'">
  <RunAOTCompilation>true</RunAOTCompilation>
  <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
</PropertyGroup>
```

The first time calling Serialize takes about > 1 second. Subsequent Serialize calls with the exact same object tree take about < 100ms.

We do not see this issue on iOS. On iOS the first call is already fast.
