### ISSUE TITLE
Add support for non-public ShouldSerialize methods

### ISSUE THREAD

**Issue by TylerBrinkley** [JamesNK/Newtonsoft.Json#1324] opened 2017-05-24 19:50 UTC
### Source/destination types

```csharp
public class ShouldSerializeNonPublicMethodClass
{
    public bool Value { get; set; }

    private bool ShouldSerializeValue() => Value;
}
```

### Source/destination JSON

```javascript
{"Value":true}
```
or
```javascript
{}
```

### Expected behavior

I expected the above destination JSON

### Actual behavior

But got
```javascript
{"Value":false}
```

### Steps to reproduce

```csharp
ShouldSerializeNonPublicMethodClass c1 = new ShouldSerializeNonPublicMethodClass
{
    Value = true
};

string json1 = JsonConvert.SerializeObject(c1, Formatting.Indented);
Assert.AreEqual(@"{
  ""Value"": true
}", json1);

ShouldSerializeNonPublicMethodClass c2 = new ShouldSerializeNonPublicMethodClass
{
    Value = false
};

string json2 = JsonConvert.SerializeObject(c2, Formatting.Indented);
Assert.AreEqual("{}", json2);
```

**Comment by JamesNK** [comment] 2017-05-28 01:10
ShouldSerialize in Json.NET is based on the same feature in XmlSerializer, and XmlSerializer requires that ShouldSerialize be public. I'd like to keep them the same.

**Comment by TylerBrinkley** [comment] 2017-05-30 18:47
Personally, I don't think serialization logic should be publicly exposed on types as it muddies up the API. Allowing them to be private prevents this. The alternative is adding an `EditorBrowsableAttribute` with a value of `None` to prevent muddying up Intellisense for consumers.

**Comment by JamesNK** [comment] 2017-05-31 04:44
I agree but the feature is designed to match what is in XmlSerializer. A contract resolver could be used to get non-public methods and set them to the contract.

**Comment by JamesNK** [comment] 2017-05-31 04:48
Maybe an attribute that could be placed on the private method? [JsonCondition]? The name of the property could either be dervived in the case of ShouldSerializePropName, or it could have a property name specified, e.g. [JsonCondition(nameof(Password))]

**Comment by TylerBrinkley** [comment] 2017-05-31 05:51
For my use case I implemented a custom contract resolver but I do like the idea of a `JsonConditionAttribute` that can be applied to any method or property. I'm not sure there'd be much value in supporting the ShouldSerialize naming convention with the new attribute though. Make it explicit and then renaming will work great using the nameof operator. A concern though is the reflection work of iterating through all of a type's methods to discover ones with the attribute. Does Json.NET already iterate through all of a type's methods?

**Comment by JamesNK** [comment] 2017-07-02 00:19
Closing as a duplicate of https://github.com/JamesNK/Newtonsoft.Json/issues/987

**Closed by JamesNK** 2017-07-02 00:19 UTC
