### ISSUE TITLE
Version 10 - Huge number of packages added to my project

### ISSUE THREAD

**Issue by tedrog36** [JamesNK/Newtonsoft.Json#1252] opened 2017-03-22 11:21 UTC
I see that version 10 has a large list of package dependencies that it didn't have before.  This results in a huge list of packages added to my project in Xamarin Studio.  Is this expected?

![screen shot 2017-03-22 at 7 20 50 am](https://cloud.githubusercontent.com/assets/3768598/24195440/1ef00f6a-0ed0-11e7-9e65-2f17a7793ca2.png)

**Comment by JamesNK** [comment] 2017-03-22 21:43
Json.NET references version 4.3.0 of packages - https://www.nuget.org/packages/Newtonsoft.Json/10.0.1

It is possible before you upgraded you weren't using a netstandard target, or Xamarin was implicitly pulling in older versions on packages but not displaying them.

I don't know Xamarin so you'll need to ask the people who make it.

**Comment by tedrog36** [comment] 2017-03-23 11:24
@JamesNK I talked with Xamarin folks first and they pointed me your way.  I'm not sure whether it is right or wrong but it makes managing packages in Xamarin Studio much more difficult.  
[https://forums.xamarin.com/discussion/91208/number-of-packages-just-exploded-with-latest-newtonsoft-json-package-update
](url)

**Comment by JamesNK** [comment] 2017-03-24 06:26
Well 9.0.1 depended on a similar list of packages - https://www.nuget.org/packages/Newtonsoft.Json/9.0.1

As far as I'm concerned Json.NET isn't doing anything wrong.

**Comment by TylerBrinkley** [comment] 2017-03-24 12:04
Perhaps it used to be binding to the PCL .NET 4.0 dll but that's been now removed so it's using the .NET Standard dll instead which carries all of those dependencies.

**Comment by dasMulli** [comment] 2017-03-24 17:59
@JamesNK the dependencies have been updated to `4.3.0` versions which will kick consuming .net core Apps out of LTS as the updated implementations will be included in the output.
See the discussion on: https://github.com/dotnet/sdk/pull/793

I suggest moving to the NETStandard.Library metapackage in version 1.6.0 so that it doesn't force updated dependencies on consuming applications.
Apps targeting `netcoreapp1.1` or using the released csproj tooling should roll forward to `1.6.1` since it is a patch release.

**Comment by dasMulli** [comment] 2017-03-24 18:09
To illustrate the problem:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.1" />
  </ItemGroup>
</Project>
```
Results in
<img width="365" alt="screen shot 2017-03-24 at 19 07 27" src="https://cloud.githubusercontent.com/assets/6129250/24307685/65959e16-10c5-11e7-8f0d-88d75a467018.png">

**Comment by JamesNK** [comment] 2017-03-26 00:50
So what is the solution here? Never reference 4.3.0 packages? That isn't going to work.

**Comment by dasMulli** [comment] 2017-03-26 06:44
> So libraries should never use a NETStandard.Library version > 1.6.0

Looks like the best choice at the moment.. If an app needs the fixes it may choose to use 1.6.1 anyway. 
The API didn't change so it shouldn't make any difference.

> .. System.Runtime.Serialization.Formatters .. only has a 4.30 package

Both `System.Runtime.Serialization.Formatters` and `System.Runtime.Serialization.Primitives` are not part of the NETStandard 1.6 contract, but they are implemented against (part of) it, so I expect them to be included in the application's output. (They aren't brought in by the `NETStandard.Library` metapackage).

For NETStandard 2.0 this is going to be much easier since the separation between reference assemblies and implementations is much better.

**Comment by JamesNK** [comment] 2017-03-26 08:40
> Both System.Runtime.Serialization.Formatters and System.Runtime.Serialization.Primitives are not part of the NETStandard 1.6 contract, but they are implemented against (part of) it, so I expect them to be included in the application's output. (They aren't brought in by the NETStandard.Library metapackage).

`System.Runtime.Serialization.Formatters` is 4.3.0 only and depends on other 4.3.0 packages. It would have to be removed along with ISerializable support or there would be a mix of dependencies.

**Comment by cremor** [comment] 2017-03-26 08:48
I'm new to .NET Standard so I'm not sure about this, but do you need to reference any package at all? Quote from the [.NET Standard FAQ](https://github.com/dotnet/standard/blob/master/docs/faq.md#should-i-reference-the-meta-package-or-should-i-reference-individual-packages):

> **Should I reference the meta package or should I reference individual packages?**
[...]
This means, you'll not have to reference any NuGet packages for .NET Standard anymore. You expressed your dependency with the lib folder, which is exactly how it has worked for all other .NET platforms, in particular .NET Framework.
However, right now our tooling will still burn in the reference to NETStandard.Library. There is no harm in that either, it will just become redundant moving forward.

Further reading:
https://docs.microsoft.com/en-us/dotnet/articles/core/packages
https://github.com/dotnet/core/blob/master/release-notes/1.0/sdk/1.0-rc3-implicit-package-refs.md

**Comment by dasMulli** [comment] 2017-03-26 15:03
Luckily, `System.Runtime.Serialization.Formatters` (and `.Primitives`) don't depend on any package that directly contains `lib` assets for `netcoreapp1.*` so it doesn't bring in a new `System.Runtime.dll` or the likes.
But it seems like this works mostly by chance and not by design..

**Comment by JamesNK** [comment] 2017-04-02 22:59
So my decision:

* Newtonsoft.Json 10.0.2 uses NETStandard.Library 1.6.1
* If you care about packages being pulled into your solution then you should either continue to use Newtonsoft.Json 9.0.1, or use a PCL assembly of Newtonsoft.Json, or update your app to use netcoreapp1.1 or above.

**Closed by JamesNK** 2017-04-02 22:59 UTC

**Comment by dagostinelli** [comment] 2017-09-24 20:53
@JamesNK  Hmm -- not a great decision.  Given the number of people who use this, the number of hours currently being spent on curating dependencies is now disproportionate to the benefit of the lib.  If it's something you can remedy, please do so.

This is also an opportunity to avoid accepting an innovation from Microsoft on the basis that is creates major headache downstream from this library as a sort of "MS needs to fix this mess first".   A reasonable solution from MS, would be a single line item in our packages.config called ".NET Standard"

In your last comment, you mentioned using a PCL of Newtonsoft.Json. How do we do that?

**Comment by dasMulli** [comment] 2017-09-24 21:11
Note that .NET Core 1.1 has been declared LTS retroactively. (likely because of issues like this)
If you update your app to netcoreapp2.0, this issue is irrelevant since the packages will be trimmed out of the dependency graph.

If for some reason you do care for removing the extra libraries on .NET Core 1.0, you can still add an explicit package reference to `NETStandard.Library` version 1.6.0 and ignore the resulting package downgrade warning. This is possible now that `Newtonsoft.Json` depends on this metapackage instead of the individual packages.

**Comment by dagostinelli** [comment] 2017-09-25 04:12
@dasMulli I went on a little hunt for the past couple of hours and found a package reference 

<package id="NETStandard.Library" version="2.0.0" targetFramework="portable45-net45+win8+wp8+wpa81" />

**Comment by dagostinelli** [comment] 2017-09-25 04:15
@dasMulli Thanks that helps.  I found the metapackage.
