### ISSUE TITLE
Missing exception documentation on 'JsonConvert.DeserializeObject'

### ISSUE THREAD

**Issue by julealgon** [JamesNK/Newtonsoft.Json#1883] opened 2018-10-15 17:35 UTC
When calling `JsonConvert.DeserializeObject<T>` (and all other overloads of `DeserializeObject`), the documentation does not state that a `ArgumentNullException` is thrown if the `input` argument is null.

The documentation should clearly state the exceptions that can be thrown by these methods and under which conditions they are thrown.

This is the code section showing the argument validation on the base method:

https://github.com/JamesNK/Newtonsoft.Json/blob/5ed873f44b6b447ccf6f8c5ce894a122656c8b63/Src/Newtonsoft.Json/JsonConvert.cs#L806-L818

Notice how the exception is not mentioned in the summary doc, so it doesn't show in the final documentation as well, for example here:
- [JsonConvert.DeserializeObject<T> Method (String)](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonConvert_DeserializeObject__1.htm)

**Comment by JamesNK** [comment] 2018-10-27 04:44
This is a low priority. PRs welcome if you feel strongly about it.

Closing as a dupe of https://github.com/JamesNK/Newtonsoft.Json/issues/1685

**Closed by JamesNK** 2018-10-27 04:44 UTC
Labels: documentation
